
version: 2

sphinx:
   configuration: docs/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
    environment: ci/requirements-py39-all.yml

python:
    version: 3.8
    install:
      - method: setuptools
        path: .

formats: []
