
version: 2

sphinx:
   configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10

conda:
    environment: ci/requirements-py39-all.yml

sphinx:
  fail_on_warning: false

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
formats: []
