
version: 2

sphinx:
   configuration: docs/conf.py

build:
  image: latest

conda:
    environment: ci/requirements-py39-all.yml

python:
    version: 3.8
    install:
      - method: setuptools
        path: .

formats: []
