name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: | 
          pip install -U poetry
        shell: bash
      - run: poetry --version
      - name: Install deps
        run: |
             poetry update python=${{ matrix.python-version }}
             poetry install --with=dev
      - name: Activate environment Unix and run coverage
        if: (${{ matrix.os }} == "ubuntu-latest") || (${{ matrix.os }} == "macos-latest")
        run: source $(poetry env info --path)/bin/activate
             poetry run coverage
      - name: Activate environment Windows and run coverage
        if: ${{ matrix.os }} == "windows-latest"
        run: source $(poetry env info --path)/Scripts/activate
             poetry run coverage
      - name: Test
        run: |
          poetry run coverage erase
          poetry run coverage run --source=./glaciersat --parallel-mode --module pytest --verbose glaciersat
          poetry run coverage combine
          poetry run coverage xml
          poetry run coverage report --skip-covered
        env:
          MPLBACKEND: agg
          COVERAGE_RCFILE: ${{ github.workspace }}/.coveragerc
      - name: Upload Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
          COVERALLS_PARALLEL: true
        run: |
          poetry remove coverage  # poetry cannot resolve both
          poetry add coveralls
          poetry run coveralls
  finish-coveralls:
    name: Coveralls Finished
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Coveralls Finished
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: |
        pip3 install --upgrade coveralls==3.2.0 &&
        coveralls --finish  
